Repository UMC-TogeDutch-Project/TogeDutch_BACKEND_JPA, pull requests merged in 2023-06, with the labels that each got.

#49 feat : 채팅 이미지 구현 #47
  TogeDutch/src/main/java/com/proj/togedutch/controller/ChatController.java
  TogeDutch/src/main/java/com/proj/togedutch/controller/PostController.java
  TogeDutch/src/main/java/com/proj/togedutch/domain/ChatMessage.java
  TogeDutch/src/main/java/com/proj/togedutch/domain/ChatPhoto.java
  TogeDutch/src/main/java/com/proj/togedutch/domain/EmailMessage.java
  TogeDutch/src/main/java/com/proj/togedutch/domain/User.java
  TogeDutch/src/main/java/com/proj/togedutch/dto/ChatPhotoDto.java
  TogeDutch/src/main/java/com/proj/togedutch/dto/UserResDto.java
  TogeDutch/src/main/java/com/proj/togedutch/repository/ChatLocationRepository.java
  TogeDutch/src/main/java/com/proj/togedutch/repository/ChatMessageRepository.java
  TogeDutch/src/main/java/com/proj/togedutch/repository/ChatPhotoRepository.java
  TogeDutch/src/main/java/com/proj/togedutch/repository/PostRepository.java
  TogeDutch/src/main/java/com/proj/togedutch/service/ChatService.java
  TogeDutch/src/main/java/com/proj/togedutch/service/EmailService.java
  TogeDutch/src/main/java/com/proj/togedutch/service/PostService.java
Labels: ✨ Feature

#50 feat : 채팅 만남 장소 구현 #48
  TogeDutch/src/main/java/com/proj/togedutch/controller/ChatController.java
  TogeDutch/src/main/java/com/proj/togedutch/domain/ChatLocation.java
  TogeDutch/src/main/java/com/proj/togedutch/dto/ChatLocationDto.java
  TogeDutch/src/main/java/com/proj/togedutch/repository/ChatLocationRepository.java
  TogeDutch/src/main/java/com/proj/togedutch/service/ChatService.java
Labels: ✨ Feature

#52 test : Swagger 설정 및 API 문서화 #51
  TogeDutch/build.gradle
  TogeDutch/src/main/java/com/proj/togedutch/config/SwaggerConfig.java
  TogeDutch/src/main/java/com/proj/togedutch/controller/PostController.java
  TogeDutch/src/main/java/com/proj/togedutch/dto/PostResDto.java
  TogeDutch/src/main/java/com/proj/togedutch/dto/UserResDto.java
Labels: ✅ Test

#53 test : Post API Swagger 문서화 #51
  TogeDutch/src/main/java/com/proj/togedutch/config/SwaggerConfig.java
  TogeDutch/src/main/java/com/proj/togedutch/controller/PostController.java
  TogeDutch/src/main/java/com/proj/togedutch/dto/CategoryReqDto.java
  TogeDutch/src/main/java/com/proj/togedutch/dto/PostReqDto.java
Labels: ✅ Test

#55 deploy : docker 설정 및 도커허브 push #54
  TogeDutch/Dockerfile
Labels: 🌏 Deploy

#80 [Feat/#6] 채팅메세지 전송 구현
  build.gradle
  src/main/java/com/proj/togedutch/controller/ChatController.java
  src/main/java/com/proj/togedutch/controller/ChatMessageController.java
  src/main/java/com/proj/togedutch/controller/ChatRoomOfUserController.java
  src/main/java/com/proj/togedutch/domain/ChatMeetTime.java
  src/main/java/com/proj/togedutch/domain/ChatMessage.java
  src/main/java/com/proj/togedutch/domain/ChatRoomOfUser.java
  src/main/java/com/proj/togedutch/dto/ChatMessageDto.java
  src/main/java/com/proj/togedutch/dto/ChatRoomOfUserResDto.java
  src/main/java/com/proj/togedutch/repository/ChatMeetTimeRepository.java
  src/main/java/com/proj/togedutch/repository/ChatMessageRepository.java
  src/main/java/com/proj/togedutch/repository/ChatRoomOfUserRepository.java
  src/main/java/com/proj/togedutch/service/ChatMessageService.java
  src/main/java/com/proj/togedutch/service/ChatRoomOfUserService.java
  src/main/java/com/proj/togedutch/service/ChatService.java
Labels: ✨ Feature
