Repository UMC-TogeDutch-Project/TogeDutch_BACKEND_JPA, pull requests merged in 2023-07, with the labels that each got.

#84 feat: ChatOfUser 구현
  src/main/java/com/proj/togedutch/controller/ChatController.java
  src/main/java/com/proj/togedutch/controller/ChatRoomOfUserController.java
  src/main/java/com/proj/togedutch/service/ChatMessageService.java
  src/main/java/com/proj/togedutch/service/ChatRoomOfUserService.java
  src/main/java/com/proj/togedutch/service/ChatService.java
Labels: ✨ Feature

#85 docs: 광고, 채팅방, 신고 swagger 설정 #mine
  src/main/java/com/proj/togedutch/config/SwaggerConfig.java
  src/main/java/com/proj/togedutch/controller/AdController.java
  src/main/java/com/proj/togedutch/controller/ChatRoomController.java
  src/main/java/com/proj/togedutch/controller/DeclarationController.java
  src/main/java/com/proj/togedutch/controller/KakaoPayController.java
  src/main/java/com/proj/togedutch/dto/AdvertisementReqDto.java
  src/main/java/com/proj/togedutch/dto/AdvertisementResDto.java
  src/main/java/com/proj/togedutch/dto/Amount.java
  src/main/java/com/proj/togedutch/dto/CardInfo.java
  src/main/java/com/proj/togedutch/dto/ChatRoomDto.java
  src/main/java/com/proj/togedutch/dto/DeclarationReqDto.java
  src/main/java/com/proj/togedutch/dto/DeclarationResDto.java
  src/main/java/com/proj/togedutch/dto/KakaoApproveResDto.java
  src/main/java/com/proj/togedutch/dto/KakaoReadyResDto.java
Labels: 📃 Docs

#86 Feat/#17
  src/main/java/com/proj/togedutch/controller/ApplicationController.java
  src/main/java/com/proj/togedutch/controller/ChatRoomController.java
  src/main/java/com/proj/togedutch/controller/LikeUsersController.java
  src/main/java/com/proj/togedutch/controller/MatchingController.java
  src/main/java/com/proj/togedutch/domain/Application.java
  src/main/java/com/proj/togedutch/dto/ApplicationWaitingReqDto.java
  src/main/java/com/proj/togedutch/dto/ApplicationWaitingResDto.java
  src/main/java/com/proj/togedutch/repository/ApplicationRepository.java
  src/main/java/com/proj/togedutch/service/ApplicationService.java
  src/main/java/com/proj/togedutch/service/MatchingService.java
Labels: 🐞 BugFix, ✨ Feature

#88 feat : 카카오 로그인 추가 #87
  src/main/java/com/proj/togedutch/controller/OAuthController.java
  src/main/java/com/proj/togedutch/domain/User.java
  src/main/java/com/proj/togedutch/dto/KakaoLoginDto.java
  src/main/java/com/proj/togedutch/dto/UserResDto.java
  src/main/java/com/proj/togedutch/service/OAuthService.java
Labels: ✨ Feature

#89 fix : @Transactional 추가, uri prefix 수정 #17
  src/main/java/com/proj/togedutch/controller/ChatController.java
  src/main/java/com/proj/togedutch/controller/ChatMessageController.java
  src/main/java/com/proj/togedutch/controller/ChatRoomController.java
  src/main/java/com/proj/togedutch/controller/ChatRoomOfUserController.java
  src/main/java/com/proj/togedutch/controller/DeclarationController.java
  src/main/java/com/proj/togedutch/controller/PostController.java
  src/main/java/com/proj/togedutch/service/ApplicationService.java
Labels: 📬 API
